import type { NextPage } from "next";
import { HarvestLayout } from "../components/Layout";
import Head from "next/head";

const ClinicInfo: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HarvestLayout>
        <div className="relative bg-white max-w-7xl mx-auto">
          <div className="lg:absolute lg:inset-0">
            <div className="lg:absolute lg:inset-y-0 lg:left-0 lg:w-1/2">
              <img
                className="h-56 w-full object-cover lg:absolute lg:h-full"
                src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1567&q=80"
                alt=""
              />
            </div>
          </div>
          <div className="relative px-4 pt-12 pb-16 sm:px-6 sm:pt-16 lg:mx-auto lg:grid lg:max-w-7xl lg:grid-cols-2 lg:px-8">
            <div className="lg:col-start-2 lg:pl-8">
              <div className="mx-auto max-w-prose text-base lg:ml-auto lg:mr-0 lg:max-w-lg">
                <h3 className="mt-2 text-3xl font-bold leading-8 tracking-tight text-gray-900 sm:text-4xl">
                  What is Harvest Free Medical Clinic?
                </h3>
                <p className="mt-8 text-lg text-gray-500">
                  Harvest Free Medical Clinic is a non-profit Christian
                  organization with 501(c)(3) status. Established by Dr. Bob
                  Freeman in February 2003, our primary volunteer staff exists
                  to share the love and truth of the Lord Jesus Christ by
                  providing free medical care and medications to those without
                  resources to pay. All individuals are eligible without regard
                  to faith, nationality, creed, or lifestyle.
                </p>
                <div className="prose prose-indigo mt-5 text-gray-500">
                  <p className="mt-8 text-lg text-gray-500">
                    Our clinic&apos;s focus is the evaluation and management of
                    chronic illnesses and preventative care, limiting specialty
                    medical/surgical referrals and acute care needs. We provide
                    Mental Health for many, but advise complex cases to enroll
                    at the County Health Department
                  </p>
                  <h3 className="mt-6 text-xl font-bold leading-8 tracking-tight text-gray-900 sm:text-4xl">
                    Clinic Info
                  </h3>
                  <p className="mt-8 text-lg text-gray-500">
                    The clinic is open 9am-4pm Monday, Tuesday and Thursday by
                    appointment only, NO WALK-INS.
                  </p>
                  <p className="mt-8 text-lg text-gray-500">
                    To contact, call (843) 747-3526 and clearly state your name,
                    phone number, and medical need. Due to volunter workforce,
                    you must leave a message on the appropriate line as there
                    are various options. Someone{" "}
                    <span className="italic">will</span> return your call, 2-3
                    attemps. &quot;Mailbox full&quot; is one of several
                    obstacles faced when contacting patients.
                  </p>
                  <p className="mt-8 text-lg text-gray-500">
                    Medication refills require 3-5 business days. Please leave a
                    message on the refill line. You will receive notification
                    when your refill will be available for pickup at the HFMC
                    pharmacy on the side of the building. If there is no
                    response after 7 days, please recall the refill line. It is
                    highly likely we have made efforts to communicate the status
                    of requested refills. Pharmacy Hours: Monday-Friday 8am-1pm
                    and 2-4pm.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </HarvestLayout>
    </>
  );
};

export default ClinicInfo;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};
