import type { NextPage } from "next";
import { HarvestLayout } from "../components/Layout";
import Head from "next/head";
import Image from "next/future/image";
import CartoonClinic from "/public/CartoonClinic.jpg";

const Eligibility: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HarvestLayout>
        <div className="relative overflow-hidden bg-white py-16 mx-auto max-w-6xl flex flex-col justify-center content-center">
          <div className="hidden lg:absolute lg:inset-y-0 lg:block lg:h-full lg:w-full lg:[overflow-anchor:none]"></div>
          <div className="relative px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-prose text-lg">
              <h1>
                <span className="mt-2 block text-center text-3xl font-bold leading-8 tracking-tight text-gray-900 sm:text-4xl">
                  Eligibility For Services
                </span>
              </h1>
            </div>
            <figure className="mt-5 border-b-2 border-b-blue-200">
              <Image
                className="w-full rounded-lg"
                src={CartoonClinic}
                alt=""
                width={1310}
                height={873}
              />
              <figcaption></figcaption>
            </figure>
            <div className="prose prose-lg prose-indigo mx-auto mt-6 text-gray-500">
              <h3 className="mt-2 text-xl font-bold leading-8 tracking-tight text-gray-900 sm:text-2xl">
                Clinic Expectations
              </h3>
              <ul role="list">
                <li className="mt-5">
                  1. Each patient is expected to participate in his/her medical
                  care to imporve their health by arriving on time for
                  appointments, taking medications as prescribe3d, adhering to
                  discussed lifestyle changes, etc
                </li>
                <li className="mt-5">2. Treat each volunteer with respect</li>
                <li className="mt-5">
                  3. Your appointment will be cancelled if you are more than 30
                  minutes late.
                </li>
                <li className="mt-5">
                  4. You are responsible for confirming or cancelling
                  appointments promptly.
                </li>
                <li className="mt-5">
                  5. Patient will inform HFMC promptly if insurance is obtained
                  (i.e. Medicaid, Medicare, Private insurance, VA benefits,
                  etc.)
                </li>
                <li className="mt-5">
                  6. HFMC does <span className="font-bold">not</span> prescribe
                  controlled substances for pain, sleep, anxiety, or ADHD.
                </li>
              </ul>

              <h3 className="mt-8 text-xl font-bold leading-8 tracking-tight text-gray-900 sm:text-2xl">
                Clinic Consequences
              </h3>
              <ul role="list">
                <li className="mt-5">
                  1. Patients not participating in their own healthcare will be
                  asked to seek care elsewhere.
                </li>
                <li className="mt-5">
                  2. Repeated missed appointments will result in loss of clinic
                  privileges
                </li>
                <li className="mt-5">
                  3. Abusive behavior whether physical or verbal will result in
                  permanent dismissal from the clinic
                </li>
              </ul>

              <blockquote className="mt-8 mb-5 border border-dashed border-slate-300 p-3">
                <p className="italic">
                  And Jesus went throughout all the cities and villages,
                  teaching in their synagogues and proclaiming the gospel of the
                  kingdom and healing every disease and every affliction. When
                  he saw the crowds, he had compassion for them, because they
                  were harassed and helpless, like sheep without a shepherd.
                  Then he said to his disciples, &quot;The harvest is plentiful,
                  but the laborers are few; therefore pray earnestly to the Lord
                  of the harvest to send out laborers into his harvest.&quot; -
                  Matthew 9:35-38 ESV
                </p>
              </blockquote>
            </div>
          </div>
        </div>
      </HarvestLayout>
    </>
  );
};

export default Eligibility;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};
