import type { NextPage } from "next";
import { HarvestLayout } from "../components/Layout";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Link from "next/link";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HarvestLayout>
        <div className="bg-white">
          <main>
            <div>
              {/* Hero card */}
              <div className="">
                <div className="mx-auto max-w-screen">
                  <div className="relative shadow-xl h-screen">
                    <div className="absolute inset-0 ">
                      <img
                        className="h-full w-full object-cover"
                        src="https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2830&q=80&sat=-100"
                        alt="People working on laptops"
                      />
                      <div className="absolute inset-0 bg-slate-400 mix-blend-multiply" />
                    </div>
                    <div className="relative h-screen w-full flex flex-col justify-center align-center content-center">
                      <h1 className="text-center text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl md:pr-22 md:pl-22 lg:pr-54 lg:pl-54 xl:pr-72 xl:pl-72">
                        <span className="block text-white">
                          Our mission is to provide excellent medical care for
                          our neighbors in need
                        </span>
                      </h1>
                      <p className="mx-auto mt-6 max-w-lg text-center text-xl text-slate-100 sm:max-w-3xl">
                        New Patient? Click{" "}
                        <Link href="/eligibility">
                          <a className="hover:underline hover:text-slate-700">
                            Here
                          </a>
                        </Link>
                      </p>
                      <div className="mx-auto mt-10 max-w-sm sm:flex sm:max-w-none sm:justify-center">
                        <div className="space-y-4 sm:mx-auto sm:gap-5 sm:space-y-0">
                          <div className="flex flex-col">
                            <p className="mx-auto mt-6 max-w-lg text-center text-xl font-bold text-slate-100 sm:max-w-3xl underline">
                              Address
                            </p>
                            <p className="mx-auto max-w-lg text-center text-xl text-slate-100 sm:max-w-3xl">
                              1670 Drydock Ave.
                            </p>
                            <p className="mx-auto max-w-lg text-center text-xl text-slate-100 sm:max-w-3xl">
                              Bldg 10-B North
                            </p>
                            <p className="mx-auto max-w-lg text-center text-xl text-slate-100 sm:max-w-3xl">
                              Charleston, SC 29405
                            </p>
                          </div>
                          <div className="flex flex-col">
                            <p className="mx-auto mt-6 max-w-lg text-center text-xl text-slate-100 sm:max-w-3xl underline">
                              Phone
                            </p>
                            <p className="mx-auto max-w-lg text-center text-xl text-slate-100 sm:max-w-3xl">
                              (843) 747 - 3526
                            </p>
                          </div>
                          <div className="flex flex-col">
                            <p className="mx-auto mt-6 max-w-lg text-center text-xl text-slate-100 sm:max-w-3xl underline">
                              Fax
                            </p>
                            <p className="mx-auto max-w-lg text-center text-xl text-slate-100 sm:max-w-3xl">
                              (843) 747 - 3527
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </main>
        </div>
      </HarvestLayout>

      {/* <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <p className="text-2xl text-gray-700">This stack uses:</p>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
          <TechnologyCard
            name="NextJS"
            description="The React framework for production"
            documentation="https://nextjs.org/"
          />
          <TechnologyCard
            name="TypeScript"
            description="Strongly typed programming language that builds on JavaScript, giving you better tooling at any scale"
            documentation="https://www.typescriptlang.org/"
          />
          <TechnologyCard
            name="TailwindCSS"
            description="Rapidly build modern websites without ever leaving your HTML"
            documentation="https://tailwindcss.com/"
          />
          <TechnologyCard
            name="tRPC"
            description="End-to-end typesafe APIs made easy"
            documentation="https://trpc.io/"
          />
          <TechnologyCard
            name="Next-Auth"
            description="Authentication for Next.js"
            documentation="https://next-auth.js.org/"
          />
          <TechnologyCard
            name="Prisma"
            description="Build data-driven JavaScript & TypeScript apps in less time"
            documentation="https://www.prisma.io/docs/"
          />
        </div>
        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
      </main> */}
    </>
  );
};

export default Home;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};
